name: Build and Release APK

permissions:
  contents: write

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '25'

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v6

      - name: Restore configuration cache
        uses: actions/cache@v5
        with:
          path: .gradle/configuration-cache
          key: ${{ runner.os }}-cc-release-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-cc-release-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android Build Tools
        run: yes | sdkmanager "build-tools;37.0.0"

      - name: Build Release APK
        run: ./gradlew --no-daemon --build-cache --configuration-cache assembleStableRelease

      - name: Sign APK
        id: sign_apk
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/apk/stable/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename signed APK
        run: |
          output="app/build/outputs/apk/stable/release/clOwOck-release.apk"
          mv "${{ steps.sign_apk.outputs.signedFile }}" "$output"
        id: rename_apk

      - name: Upload Signed APK to Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/stable/release/clOwOck-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Unsigned APK as Artifact
        uses: actions/upload-artifact@v7
        with:
          name: unsigned-stable-apk
          path: app/build/outputs/apk/stable/release/*-unsigned.apk
